### ISSUE TITLE
Error with QAP Build #2

### ISSUE THREAD

**Issue by hebbianloop** [preprocessed-connectomes-project/quality-assessment-protocol#103]
Attempting to install from source with python 3.4 installed via  mac ports.  Using nipype version 0.12.1.

Ran the following ::

`git clone https://github.com/preprocessed-connectomes-project/quality-assessment-protocol.git
`
`python3 setup.py install
`

Get the error ::

`Traceback (most recent call last):
  File "setup.py", line 78, in <module>
    main()
  File "setup.py", line 9, in main
    version=__version__,
NameError: name '__version__' is not defined`

**Comment by cirongliu** [comment]
same error here. how to solve it?
