### ISSUE TITLE
Error using qap_measures_pipeline

### ISSUE THREAD

**Issue by tragus1** [preprocessed-connectomes-project/quality-assessment-protocol#120]
Traceback (most recent call last):
  File "/home/demenzbild/anaconda2/bin/qap_measures_pipeline.py", line 10, in <module>
    obj.run()
  File "/home/demenzbild/anaconda2/lib/python2.7/site-packages/qap/cli.py", line 552, in run
    from nipype.pipeline.plugins.callback_log import log_nodes_cb
ImportError: No module named callback_log

Can you pleas help me solving this issue?

Thanks

**Comment by rpcary** [comment]
Same problem. 
Suspected it was a problem with the nipype fork (nipype==1.0.4.dev0) that came with qap==1.0.8. If I go into python, the nipype 'plugins' module looks ...incomplete. Not sure if I'm missing something there, but I don't see any failures in the installation.
i.e. from python:
import nipype.pipeline.plugins
>>> dir(nipype.pipeline.plugins)
['__doc__', '__file__', '__name__', '__package__', '__path__']

Also, checking .../python2.7/site-packages/nipype-1.0.4_dev-py2.7.egg/nipype/pipeline/plugins/ 
there is nothing by the name (or via grep containing) "callback_log". 

Furthermore, trying a different version of nipype (0.12.1 vs. 1.0.4.dev0), gives me a different error (related to poor option selection in my configuration settings), and the process at least moves on to creating folders.

Running on a CentOS Linux release 7.5.1804 with python 2.7.

**Comment by stefanotambalo** [comment]
Same problem here.

Thanks for any new input on this.

**Comment by anibalsolon** [comment]
Hi @tragus1 @rpcary @stefanotambalo 

You should install `nipype==0.13.1` to get it working:
```
pip uninstall nipype
pip install nipype==0.13.1
```

It will remedy the situation. We are working on improve this scenario.

**Comment by stefanotambalo** [comment]
Thank you very much!

I'm going to give it a try.


S.

________________________________

**Comment by stefanotambalo** [comment]
Hi, I'm still struggling with runtime errors.
I'm running QAP in a 2.7 virtual env, when I launch the script qap_measures_pipeline, it systematically crashes returning (not considering FutureWarning):

[...]
from nipype.pipeline.plugins.callback_log import log_nodes_cb
ImportError: No module named callback_log
[...]

from cli.py.

Any suggestion/solution?
Thanks in advance.

**Comment by anibalsolon** [comment]
Hi Stefano,

could you please run this command in your virtual env?

```
python -c "import nipype; print(nipype.__version__)"
```

Thanks

Anibal Solon
Assistant Research Scientist
Computational Neuroimaging Laboratory
p: 646.625.4378
e: anibal.solon@childmind.org <steven.giavasis@childmind.org>

Child Mind Institute
445 Park Avenue (entrance on 56th Street)
New York, NY 10022
childmind.org <https://aidbox.org/ct/?i=638132000000914&t=1>


Em qui, 6 de set de 2018 às 07:04, Stefano Tambalo <notifications@github.com>
escreveu:

**Comment by stefanotambalo** [comment]
Hi Anibal, sorry for the huge delay.
Here's the output in 2.7 virtual env:

/home/*********/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
0.12.1

Thanks!

**Comment by anibalsolon** [comment]
Hi @stefanotambalo 

the output suggests that you are using an older version of nipype (0.12.1). We recommend you to install the version 0.13.1:

```
pip install nipype==0.13.1
```

Thank you

**Comment by stefanotambalo** [comment]
That's what I did following your previous message. Then I downgraded to 0.12 for some reasons. Now I've put 0.13 back on, but still running into the same problem.

Here's the entire output:

`/home/stefano/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/stefano/anaconda3/envs/py27/lib/python2.7/site-packages/bids/grabbids/__init__.py:6: FutureWarning: grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8
  warnings.warn("grabbids has been renamed to layout in version 0.6.5, and will be removed in version 0.8", FutureWarning)
Traceback (most recent call last):
  File "/home/stefano/anaconda3/envs/py27/bin/qap_measures_pipeline.py", line 4, in <module>
    __import__('pkg_resources').run_script('qap==1.0.8b0', 'qap_measures_pipeline.py')
  File "/home/stefano/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/stefano/anaconda3/envs/py27/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/home/stefano/anaconda3/envs/py27/lib/python2.7/site-packages/qap-1.0.8b0-py2.7.egg/EGG-INFO/scripts/qap_measures_pipeline.py", line 10, in <module>
    obj.run()
  File "/home/stefano/anaconda3/envs/py27/lib/python2.7/site-packages/qap-1.0.8b0-py2.7.egg/qap/cli.py", line 552, in run
    from nipype.pipeline.plugins.callback_log import log_nodes_cb
ImportError: No module named callback_log`

Can you spot something useful to fix the problem?
Thanks.
S.

**Comment by anibalsolon** [comment]
Hi @stefanotambalo

it still looks like a nipype version problem. 

To reproduce the error outside qap, you can run:

```
import nipype 
print("Nypipe version", nipype.__version__) 
print(nipype.__file__)
from nipype.pipeline.plugins.callback_log import log_nodes_cb
```

Please send us the output so we can try to identify the problem origin.

**Comment by stefanotambalo** [comment]
Hi @anibalsolon,

here's the output:

`/home/stefano/anaconda3/envs/py27/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
('Nypipe version', u'0.13.1')
/home/stefano/anaconda3/envs/py27/lib/python2.7/site-packages/nipype/__init__.pyc
`
Is it useful?
S.
