### ISSUE TITLE
Error running qap_measures_pipeline

### ISSUE THREAD

**Issue by ghost** [preprocessed-connectomes-project/quality-assessment-protocol#125]
I recently installed QAP. I've tried running it on 4 different machines (2 MacOS, 1 neurodebian VM, and 1 Ubuntu VM). It always gives an error when trying to run. I get stuck in the same place this other user did: https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/issues/86

The error comes when running nipype 0.13.1

However, a downgrade to nipype 0.12.1 results in the error discussed here: https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/issues/120

At that point it's just a vicious cycle of error messages. Any suggestions?

```
Traceback (most recent call last):
  File "/usr/local/bin/qap_measures_pipeline.py", line 10, in <module>
    obj.run()
  File "/usr/local/lib/python2.7/dist-packages/qap/cli.py", line 611, in run
    results.append(self.run_one_bundle(idx))
  File "/usr/local/lib/python2.7/dist-packages/qap/cli.py", line 446, in run_one_bundle
    rt = run_workflow(wfargs)
  File "/usr/local/lib/python2.7/dist-packages/qap/cli.py", line 879, in run_workflow
    config, name)
  File "/usr/local/lib/python2.7/dist-packages/qap/qap_workflows.py", line 407, in qap_anatomical_spatial_workflow
    qap_mask_workflow(workflow, resource_pool, config, name)
  File "/usr/local/lib/python2.7/dist-packages/qap/qap_workflows.py", line 74, in qap_mask_workflow
    config, name)
  File "/usr/local/lib/python2.7/dist-packages/qap/anatomical_preproc.py", line 371, in afni_anatomical_linear_registration
    config, name)
  File "/usr/local/lib/python2.7/dist-packages/qap/anatomical_preproc.py", line 58, in anatomical_reorient_workflow
    anat_deoblique = pe.Node(interface=preprocess.Refit(),
AttributeError: 'module' object has no attribute 'Refit'
```

Thanks!

**Comment by Romantic-Pumpkin** [comment]
i think you should install nipype in version 0.12.1 and networkx in version 1.11 to slove this problem， may it help you
