### ISSUE TITLE
[BUG] IOError: Duplicate node name datasink_qap_mosaic found.

### ISSUE THREAD

**Issue by oesteban** [preprocessed-connectomes-project/quality-assessment-protocol#35]
I will fix this as soon as I confirm my hypothesis: the sink node is added twice if `write_all_outputs` and  `write_report` are `true` simultaneously.

**Comment by chrisgorgo** [comment]
@craigmoodie also run into this:

```
{'pipeline_config_yaml': 'CNI_anatomical.qap_config.yml', 'write_all_outputs': True, 'num_subjects_at_once': 16, 'output_directory': '/scratch/PI/russpold/work/CNI/qap_output_dir', 'write_report': True, 'working_directory': '/scratch/PI/russpold/work/CNI/qap_working_dir', 'num_cores_per_subject': 1, 'template_skull_for_anat': '/share/sw/free/fsl/5.0.7/fsl/data/standard/MNI152_T1_2mm.nii.gz', 'template_brain_for_anat': '/share/sw/free/fsl/5.0.7/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz', 'qap_type': 'anatomical_spatial'}
Traceback (most recent call last):
  File "/share/PI/russpold/software/anaconda/bin/qap_anatomical_spatial.py", line 16, in <module>
    obj.run()
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/qap/cli.py", line 244, in run
    results = self._run_here(run_name)
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/qap/cli.py", line 187, in _run_here
    results = pool.map(_run_workflow, wfargs)
  File "/share/PI/russpold/software/anaconda/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/share/PI/russpold/software/anaconda/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: Duplicate node name datasink_qap_mosaic found.
```
