### ISSUE TITLE
[BUG] Runtime Error 

### ISSUE THREAD

**Issue by craigmoodie** [preprocessed-connectomes-project/quality-assessment-protocol#37]
151125-10:48:18,896 workflow INFO:
     Executing node func_reorient in dir: /scratch/PI/russpold/work/CNI/qap_working_dir/sub-002/session_1/func_4/func_reorient
151125-10:48:18,906 workflow INFO:
     Running: 3dresample -orient RPI -prefix sub-002_task-protocol_dev_run-4_bold_calc_resample.nii.gz -inset /scratch/PI/russpold/work/CNI/qap_working_dir/sub-002/session_1/func_4/func_reorient/sub-002_task-protocol_dev_run-4_bold_calc.nii.gz
151125-10:48:46,102 workflow ERROR:
     ['Node func_reorient failed to run on host sh-5-35.local.']
151125-10:48:46,132 workflow INFO:
     Saving crash info to /scratch/PI/russpold/work/CNI/qap_output_dir/crash-20151125-104846-cmoodie-func_reorient.pklz
151125-10:48:46,132 workflow INFO:
     Traceback (most recent call last):
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 38, in run
    node.run(updatehash=updatehash)
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1428, in run
    self._run_interface()
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1538, in _run_interface
    self._result = self._run_command(execute)
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 1664, in _run_command
    result = self._interface.run()
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1033, in run
    runtime = self._run_wrapper(runtime)
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1457, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1491, in _run_interface
    self.raise_exception(runtime)
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1415, in raise_exception
    raise RuntimeError(message)
RuntimeError: Command:
3dresample -orient RPI -prefix sub-002_task-protocol_dev_run-4_bold_calc_resample.nii.gz -inset /scratch/PI/russpold/work/CNI/qap_working_dir/sub-002/session_1/func_4/func_reorient/sub-002_task-protocol_dev_run-4_bold_calc.nii.gz
Standard output:

Standard error:

Return code: -9
Interface Resample failed to run. 

151125-10:48:46,136 workflow INFO:
     ***********************************
151125-10:48:46,136 workflow ERROR:
     could not run node: func_4.func_reorient
151125-10:48:46,137 workflow INFO:
     crashfile: /scratch/PI/russpold/work/CNI/qap_output_dir/crash-20151125-104846-cmoodie-func_reorient.pklz
151125-10:48:46,137 workflow INFO:
     ***********************************
Traceback (most recent call last):
  File "/share/PI/russpold/software/anaconda/bin/qap_functional_spatial.py", line 16, in <module>
    obj.run()
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/qap/cli.py", line 244, in run
    results = self._run_here(run_name)
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/qap/cli.py", line 178, in _run_here
    results.append(_run_workflow(a))
  File "/share/PI/russpold/software/anaconda/lib/python2.7/site-packages/qap/cli.py", line 426, in _run_workflow
    rt.update({'status': 'failed', 'msg': e.msg})
AttributeError: 'exceptions.RuntimeError' object has no attribute 'msg'

**Comment by craigmoodie** [comment]
This error occurred using a pip installed version of the master

**Comment by chrisgorgo** [comment]
Maybe it's something with the data or AFNI installation? Did you try going to `/scratch/PI/russpold/work/CNI/qap_working_dir/sub-002/session_1/func_4/func_reorient` and running:

```
3dresample -orient RPI -prefix sub-002_task-protocol_dev_run-4_bold_calc_resample.nii.gz -inset /scratch/PI/russpold/work/CNI/qap_working_dir/sub-002/session_1/func_4/func_reorient/sub-002_task-protocol_dev_run-4_bold_calc.nii.gz
```

**Comment by chrisgorgo** [comment]
FYI that was a memory related issue.

**Comment by craigmoodie** [comment]
Yes, users should be mindful of the size of the files being processed relative to the number of cores requested per subject in the current version of the config.
