### ISSUE TITLE
[BUG] runner object for pipeline engine is being viewed as a tuple

### ISSUE THREAD

**Issue by jpellman** [preprocessed-connectomes-project/quality-assessment-protocol#41]
A number of runs are failing on one of our servers.  This can't be reproduced on a local machine.  The error appears as follows:

Traceback (most recent call last):
  File "/home/jpellman/miniconda/envs/qap_105_test/bin/qap_functional_spatial.py", line 16, in <module>
    obj.run()
  File "/home/jpellman/miniconda/envs/qap_105_test/lib/python2.7/site-packages/qap/cli.py", line 244, in run
    results = self._run_here(run_name)
  File "/home/jpellman/miniconda/envs/qap_105_test/lib/python2.7/site-packages/qap/cli.py", line 178, in _run_here
    results.append(_run_workflow(a))
  File "/home/jpellman/miniconda/envs/qap_105_test/lib/python2.7/site-packages/qap/cli.py", line 423, in _run_workflow
    workflow.run(**runargs)
  File "/home/jpellman/miniconda/envs/qap_105_test/lib/python2.7/site-packages/nipype/pipeline/engine.py", line 701, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
AttributeError: 'tuple' object has no attribute 'run'

This might have something to do with the build of nipype used in the environment I set up (0.11.0), although probably not since this is the same version of nipype I used on the local machine.

**Comment by jpellman** [comment]
The error closely follows the generation of the png file from the dot file describing the workflow.

**Comment by oesteban** [comment]
Hi @jpellman, I'll take on this ASAP. Yes, you're right, looks like a problem with nipype since it's trying to call the `run()` member of the workflow.

**Comment by oesteban** [comment]
Hi @jpellman, may you check if #44 fixes this bug?
