### ISSUE TITLE
Error after writing PDF reports..

### ISSUE THREAD

**Issue by dbkeator** [preprocessed-connectomes-project/quality-assessment-protocol#50]
Hi,
I tried a simple single-subject anatomical report using the abide spatial config with appropriate edits given my environment.  I had a similar problem on another machine.  Any thoughts on what the issue might be?

[dbkeator@nicfs site_anat]$ qap_anatomical_spatial.py --sublist ./test.yaml /data/soft/quality-assessment-protocol-master/configs/qap_config_abide_spatial_dbk.yml --with-reports
/usr/local/lib/python2.7/site-packages/pycrypto-2.6.1-py2.7-linux-x86_64.egg/Crypto/Util/number.py:57: PowmInsecureWarning: Not using mpz_powm_sec.  You should rebuild using libgmp >= 5 to avoid timing attack vulnerability.
160427-15:23:12,335 workflow INFO:
     There are 1 subjects in the pool
160427-15:23:12,534 workflow INFO:
     Pipeline start time: 2016-04-27_15:23:12
160427-15:23:12,534 workflow INFO:
     Contents of resource pool:
{'anatomical_scan': '/data/home/dbkeator/qap_tests/site_anat/sub-000974039052/ses0002/anatomy/000974039052_ses0002_t1.nii.gz'}
160427-15:23:12,534 workflow INFO:
     Configuration settings:
{'write_graph': True, 'write_all_outputs': False, 'num_subjects_at_once': 1, 'output_directory': '/data/home/dbkeator/qap_tests/output', 'write_report': True, 'working_directory': '/data/home/dbkeator/qap_tests/working', 'num_cores_per_subject': '1`', 'template_skull_for_anat': '/data/soft/fsl/data/standard/MNI152_T1_2mm.nii.gz', 'pipeline_config_yaml': '/data/soft/quality-assessment-protocol-master/configs/qap_config_abide_spatial_dbk.yml', 'template_brain_for_anat': '/data/soft/fsl/data/standard/MNI152_T1_2mm_brain.nii.gz', 'qap_type': 'anatomical_spatial'}
160427-15:23:14,847 workflow INFO:
     Converting dotfile: /data/home/dbkeator/qap_tests/output/qap_config_abide_spatial_dbk/sub-000974039052/ses0002/anatomy/qap_config_abide_spatial_dbk.dot to png format
160427-15:23:14,865 workflow INFO:
     ['check', 'execution', 'logging']
160427-15:23:14,889 workflow INFO:
     Elapsed time (minutes) since last start: 0.0392481486003
160427-15:23:14,889 workflow INFO:
     Pipeline end time: 2016-04-27_15:23:14
160427-15:23:14,890 workflow INFO:
     Writing PDF reports
Traceback (most recent call last):
  File "/usr/local/bin/qap_anatomical_spatial.py", line 4, in <module>
    **import**('pkg_resources').run_script('qap==1.0.5', 'qap_anatomical_spatial.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/EGG-INFO/scripts/qap_anatomical_spatial.py", line 10, in <module>
    obj.run()
  File "/usr/local/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/qap/cli.py", line 253, in run
    out_dir=config['output_directory'])
  File "/usr/local/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/qap/viz/reports.py", line 38, in workflow_report
    df = pd.read_csv(in_csv, dtype={'subject': str}).sort(
  File "/usr/local/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 529, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 295, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 612, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 747, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/site-packages/pandas-0.18.0-py2.7-linux-x86_64.egg/pandas/io/parsers.py", line 1119, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 353, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:3246)
  File "pandas/parser.pyx", line 591, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:6111)
IOError: File /data/home/dbkeator/qap_tests/output/qap_anatomical_spatial.csv does not exist
[dbkeator@nicfs site_anat]$

**Comment by jpellman** [comment]
Hi @dbkeator ,

We've encountered this issue before with someone running QAP using a configuration file that specified more cores than are available on a machine.  Could you double-check that this isn't the case for this run?

You may also want to join our [forum](https://groups.google.com/d/forum/pcp_forum) and follow the thread [here](https://groups.google.com/forum/#!searchin/pcp_forum/dot/pcp_forum/hpr1AaVPn-s/g-qIPD-SGQAJ), since it discusses the same issue in more depth.

**Comment by dbkeator** [comment]
I was worried about that so I dropped the requested cores/subject to 1 just to be safe.  Interestingly, I just checked the config file and although it was set to 1 it had an errant character and was set to " 1` ".  I just fixed that and it seems to be running now.  Thanks for the help!  I'll join the forum as well, thanks for the link..

**Comment by jpellman** [comment]
This might be a larger issue with how the command line utilities in QAP 1.0.5 handle multicore runs.  I attempted to replicate this on our own cluster and found that only when I set _num_cores_per_subject_ to 1 were the command line utilities able to execute the pipeline.

**Comment by sgiavasis** [comment]
This is no longer an issue in 1.0.6_dev_parallel, which will be in the next release.
