### ISSUE TITLE
Error with write_reports functionality

### ISSUE THREAD

**Issue by jpellman** [preprocessed-connectomes-project/quality-assessment-protocol#51]
One of our users from the forum received the following error when running the anatomical measures on 2 scans with the violin plots toggled to True.  The commit message for the code implicated is "add stripplot for N < 4", which leads me to believe that number of scans may be implicated. 

Traceback (most recent call last):
  File "/Users/varadajc/Envs/qcp3/bin/qap_anatomical_spatial.py", line 4, in <module>
    **import**('pkg_resources').run_script('qap==1.0.5', 'qap_anatomical_spatial.py')
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/pkg_resources/**init**.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/EGG-INFO/scripts/qap_anatomical_spatial.py", line 10, in <module>
    obj.run()
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/qap/cli.py", line 258, in run
    out_dir=config['output_directory'])
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/qap/viz/reports.py", line 131, in workflow_report
    func(df, subject=subid, out_file=qc_ms)
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/qap/viz/reports.py", line 340, in qap_anatomical_spatial
    out_file=out_file)
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/qap/viz/reports.py", line 249, in _write_report
    title='QC measures ' + subtitle)
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/qap-1.0.5-py2.7.egg/qap/viz/plotting.py", line 125, in plot_all
    zorder=10)
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/matplotlib/__init__.py", line 1812, in inner
    return func(ax, _args, *_kwargs)
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 1424, in plot
    for line in self._get_lines(_args, *_kwargs):
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 386, in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 364, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/Users/varadajc/Envs/qcp3/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 223, in _xy_from_xy
    raise ValueError("x and y must have same first dimension")
ValueError: x and y must have same first dimension

**Comment by sgiavasis** [comment]
I have resolved this issue, and the fix will be in the upcoming release.
