### ISSUE TITLE
Run Time Error 7m** FATAL ERROR value too large

### ISSUE THREAD

**Issue by hebbianloop** [preprocessed-connectomes-project/quality-assessment-protocol#58]
[link to .pklz](https://drive.google.com/file/d/0B62ZUf2RblCDRE5idW13cXpGaWc/view?usp=sharing)
# Standard Error Output:

160807-20:48:40,166 interface INFO:
     stderr 2016-08-07T20:48:39.992265:++ Oblique dataset:/Volumes/Archive.ADS/ADS/analysis/qap/werk/C70550/w1/GoNoGo_2/func_slice_time_correction/EP-ep2d_3.nii.gz is 8.499994 degrees from plumb.
160807-20:48:40,166 interface INFO:
     stderr 2016-08-07T20:48:39.992265:[7m*\* FATAL ERROR:[0m -ignore value 0 is too large
160807-20:48:40,167 interface INFO:
     stderr 2016-08-07T20:48:39.992265:*\* Program compile date = Aug  2 2016
160807-20:48:40,670 workflow ERROR:
     ['Node func_slice_time_correction failed to run on host trash-can.local.']
160807-20:48:40,671 workflow INFO:
     Saving crash info to /Volumes/Archive.ADS/ADS/analysis/qap/crash-20160807-204840-shad-func_slice_time_correction-b20c6ded-e1a8-45c6-bf31-9852d310a44c.pklz
160807-20:48:40,672 workflow INFO:
     Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 39, in run
    node.run(updatehash=updatehash)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 394, in run
    self._run_interface()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 504, in _run_interface
    self._result = self._run_command(execute)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 630, in _run_command
    result = self._interface.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1043, in run
    runtime = self._run_wrapper(runtime)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1660, in _run_wrapper
    runtime = self._run_interface(runtime)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/afni/base.py", line 128, in _run_interface
    return super(AFNICommandBase, self)._run_interface(runtime)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1694, in _run_interface
    self.raise_exception(runtime)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nipype/interfaces/base.py", line 1618, in raise_exception
    raise RuntimeError(message)
RuntimeError: Command:
3dTshift -prefix EP-ep2d_3_tshift.nii.gz /Volumes/Archive.ADS/ADS/analysis/qap/werk/C70550/w1/GoNoGo_2/func_slice_time_correction/EP-ep2d_3.nii.gz
Standard output:

Standard error:
++ 3dTshift: AFNI version=AFNI_16.2.07 (Aug  2 2016) [64-bit]
[7m_\+ WARNING:[0m   If you are performing spatial transformations on an oblique dset, 
  such as /Volumes/Archive.ADS/ADS/analysis/qap/werk/C70550/w1/GoNoGo_2/func_slice_time_correction/EP-ep2d_3.nii.gz,
  or viewing/combining it with volumes of differing obliquity,
  you should consider running: 
     3dWarp -deoblique 
  on this and  other oblique datasets in the same session.
 See 3dWarp -help for details.
++ Oblique dataset:/Volumes/Archive.ADS/ADS/analysis/qap/werk/C70550/w1/GoNoGo_2/func_slice_time_correction/EP-ep2d_3.nii.gz is 8.499994 degrees from plumb.
[7m_\* FATAL ERROR:[0m -ignore value 0 is too large
*\* Program compile date = Aug  2 2016
Return code: 1
Interface TShift failed to run. 

160807-20:48:40,686 workflow INFO:
     ***********************************
160807-20:48:40,687 workflow ERROR:
     could not run node: GoNoGo_2.func_slice_time_correction
160807-20:48:40,687 workflow INFO:
     crashfile: /Volumes/Archive.ADS/ADS/analysis/qap/crash-20160807-204840-shad-func_slice_time_correction-b20c6ded-e1a8-45c6-bf31-9852d310a44c.pklz
160807-20:48:40,688 workflow INFO:
     ***********************************
Traceback (most recent call last):
  File "/Users/shad/quality-assessment-protocol/scripts/qap_functional_spatial.py", line 10, in <module>
    obj.run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py", line 244, in run
    results = self._run_here(run_name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/qap/cli.py", line 187, in _run_here
    results = pool.map(_run_workflow, wfargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
AttributeError: 'exceptions.RuntimeError' object has no attribute 'msg'

**Comment by sgiavasis** [comment]
Hi Seldamat,

Can you re-run this with "write_all_outputs" set to True until it crashes again? I'd like for us to take a look at one of the intermediary files that is one step before 3dTshift.

**Comment by hebbianloop** [comment]
Sure! I'll rerun it this afternoon and update this post.  Which file would you like to see? There is also a .pklz file that is produced.

**Comment by sgiavasis** [comment]
I was thinking of trying this command again, from command line:

3dTshift -prefix EP-ep2d_3_tshift.nii.gz /Volumes/Archive.ADS/ADS/analysis/qap/werk/C70550/w1/GoNoGo_2/func_slice_time_correction/EP-ep2d_3.nii.gz

You would need that "func_slice_time_correction" intermediary file in order to do so. Note, if you try to run 1.0.6_dev_parallel like I mentioned in the other issue, this intermediary step will no longer be there, so I am not sure if you would still see this issue.

**Comment by hebbianloop** [comment]
Ok, I am running on 1.0.6_dev_parallel -- I'll let you know if this issue comes up again.  I tried rerunning but the pipeline crashed out at PDF writing (accidentally left it at True)

**Comment by sgiavasis** [comment]
Hi seldamat,

If you re-install QAP one more time (from 1.0.6_dev_parallel), and re-run, let me know if you still get the PDF crashes. And if you do, what the error is.

Thank you!

**Comment by hebbianloop** [comment]
Ok I will try this again -- I think I ran into some other issues but I haven't had a chance to follow up with it.  I will post back here once the run is complete.

**Comment by hebbianloop** [comment]
Hi sgiavasis -- I've reinstalled and tried to test the PDF crashes however I keep getting a type error that disallows me to do any testing of this bug report

**Comment by sgiavasis** [comment]
Can you send me what the crash says?

**Comment by sgiavasis** [comment]
@jpellman We should do some final runs/checks on this to make extra sure it's not still happening.
